# package name
name: io.codeblaze.templates
# package display name
displayName: CodeBlaze Templates
# package description
description: Monobehaviours starting points for common types of games
# repository url
repoUrl: 'https://github.com/BLaZeKiLL/CodeBlazeLibrary'
# forked repository url
parentRepoUrl: null
# spdx license id
licenseSpdxId: MIT
# license name
licenseName: MIT License
# list of topic slugs
topics:
  - utilities
# Filter Git tags based on prefix. Used by monorepos to separate pacakges
gitTagPrefix: 'templates'
# A regular expression to ignore Git tags
gitTagIgnore: '-master$'
# Minimal version to build
minVersion: '1.0.0'
# readme path
readme: 'upm/templates:README.md'
# package hunter name (github username)
hunter: BLaZeKiLL